default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: cmw_dev

test:
  <<: *default
  database: cmw_test

production: 
  <<: *default
  database: cmw_production